# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [39]:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

# Expected Output:
# Given list: [10, 20, 30, 40, 10]
def check(numbers_x):
    if numbers_x[0]==numbers_x[-1]:
        print("True")
    else:
        print("\n")
        print("False")

print(check(numbers_x))
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False
print(check(numbers_y))

True
None


False
None






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [2]:
#code here
import numpy as np
x= np.array([1,2,3])
y= np.array([3,5,6])

sum=x+y
print("Element-wise addition result:")
print(sum)

product=x*y
print("Element-wise multiplication result:")
print(product)


Element-wise addition result:
[4 7 9]
Element-wise multiplication result:
[ 3 10 18]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [3]:
import numpy as np

x=np.array([1,2,3,4,5,6,7,8,9])
y=np.reshape(x, (3, 3))
print("Reshaped array:")
print(y)

#arrays for concatenation
array1=np.array([[1,2,3],
                   [4,5,6]])
array2=np.array([[7,8,9],
                   [10,11,12]])

#horizontally
hori= np.concatenate((array1, array2), axis=1)
print("Horizontal :")
print(hori)

#vertically
vertical=np.concatenate((array1, array2), axis=0)
print("Vertical : ")
print(vertical)


Reshaped array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Horizontal :
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertical : 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [8]:
def classify_emails(emails):
    imp_key = ['urgent', 'important', 'importance']
    spam_key = ['free', 'luckydraw', 'click here']
    prom_key = ['deal', 'promotion']
    imp_emails = []
    spam_emails = []
    prom_emails = []

    for email in emails:
        if any(keyword in email.lower() for keyword in imp_key):
            imp_emails.append(email)
        elif any(keyword in email.lower() for keyword in prom_key):
            prom_emails.append(email)
        elif any(keyword in email.lower() for keyword in spam_key):
            spam_emails.append(email)

    return imp_emails, prom_emails, spam_emails

# Emails
emails = [
    "Important: Please review and take action",
    "Special offer: 50% off on selected items",
    "You've won the lottery!",
    "Urgent: Your attention is required",
    "Inheritance claim notification",
    "Check out this amazing deal",
    "Important notice: Account security update",
    "Free gift with purchase. Click here!"
]

#classifying emails
important, promotions, spam = classify_emails(emails)

#printing the lists
print("Important Emails:")
for email in important:
    print(email)
#promotion
print("Promotions Emails:")
for email in promotions:
    print(email)
#spam
print("Spam Emails:")
for email in spam:
    print(email)


Important Emails:
Important: Please review and take action
Urgent: Your attention is required
Important notice: Account security update
Promotions Emails:
Check out this amazing deal
Spam Emails:
Free gift with purchase. Click here!


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [11]:
#code here
#dictionary for spanish words
d={}
d['hello']='hola'
d['goodbye']='adios'
d['thankyou']='gracias'
d['yes']='si'
d['no']='no'
d['okay']='bueno'
while True:
    word = input("Enter an English word or 'q' to quit: ")

    #if the user wants to quit
    if word.lower() == 'q':
        print("Goodbye!")
        break

    #if the word exists in the dictionary
    if word in d:
        print("Spanish translation:",d[word])
    else:
        print("Translation not available.")


Enter an English word (or 'q' to quit): hello
Spanish translation: hola
Enter an English word (or 'q' to quit): yes
Spanish translation: si
Enter an English word (or 'q' to quit): 1
Translation not available.
Enter an English word (or 'q' to quit): q
Goodbye!


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [15]:
import pandas as pd
url="https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df=pd.read_csv(url)
df=pd.DataFrame(df)
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [16]:
#total global sales
total_global_sales = df['Global_Sales'].sum()
print(total_global_sales)

8920.44


In [17]:
#the game with the highest global sales
highest_game = df.loc[df['Global_Sales'].idxmax()]
print("Game with the highest global sales:")
print(highest_game)

Game with the highest global sales:
Rank                     1
Name            Wii Sports
Platform               Wii
Year                2006.0
Genre               Sports
Publisher         Nintendo
NA_Sales             41.49
EU_Sales             29.02
JP_Sales              3.77
Other_Sales           8.46
Global_Sales         82.74
Name: 0, dtype: object


In [18]:
#the average sales for each region
average_sales = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("Average sales :")
print(average_sales)

Average sales :
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64


In [26]:
#top 5 most popular game genres based on global sales
top_genres = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("Top 5 most popular game genres:")
print(top_genres)

Top 5 most popular game genres:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [27]:
#the total sales for each genre in each region
total_salesregion = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
genre_na = total_salesregion['NA_Sales'].idxmax()
print("Most popular genre in North America:",genre_na)


Most popular genre in North America: Action


In [28]:
#last 10 rows
print("Last 10 rows:")
print(df.tail(10))


Last 10 rows:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
1

In [30]:

#top 3 gaming platforms with the highest global sales
top_platforms = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print(top_platforms)


Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [31]:

#market share (percentage of global sales) for each genre
market_share = (df.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print("Market share for each genre:")
print(market_share)


Market share for each genre:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [33]:
#correlation coefficient 
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print(correlation_coefficient)


0.7677267483702636
